#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/UML

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/UML

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/Etat/Figer.o $(OBJDIR_DEBUG)/Etat/EtatRobot.o $(OBJDIR_DEBUG)/Etat/EnRoute.o $(OBJDIR_DEBUG)/Etat/EnChargeFacePlot.o $(OBJDIR_DEBUG)/Etat/EnCharge.o $(OBJDIR_DEBUG)/BaseRobot/Objet.o $(OBJDIR_DEBUG)/Etat/AVideFacePlot.o $(OBJDIR_DEBUG)/Etat/AVide.o $(OBJDIR_DEBUG)/BaseRobot/Robot.o $(OBJDIR_DEBUG)/BaseRobot/Position.o $(OBJDIR_DEBUG)/BaseRobot/Plot.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/Etat/Figer.o $(OBJDIR_RELEASE)/Etat/EtatRobot.o $(OBJDIR_RELEASE)/Etat/EnRoute.o $(OBJDIR_RELEASE)/Etat/EnChargeFacePlot.o $(OBJDIR_RELEASE)/Etat/EnCharge.o $(OBJDIR_RELEASE)/BaseRobot/Objet.o $(OBJDIR_RELEASE)/Etat/AVideFacePlot.o $(OBJDIR_RELEASE)/Etat/AVide.o $(OBJDIR_RELEASE)/BaseRobot/Robot.o $(OBJDIR_RELEASE)/BaseRobot/Position.o $(OBJDIR_RELEASE)/BaseRobot/Plot.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/Etat || mkdir -p $(OBJDIR_DEBUG)/Etat
	test -d $(OBJDIR_DEBUG)/BaseRobot || mkdir -p $(OBJDIR_DEBUG)/BaseRobot

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/Etat/Figer.o: Etat/Figer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/Figer.cpp -o $(OBJDIR_DEBUG)/Etat/Figer.o

$(OBJDIR_DEBUG)/Etat/EtatRobot.o: Etat/EtatRobot.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/EtatRobot.cpp -o $(OBJDIR_DEBUG)/Etat/EtatRobot.o

$(OBJDIR_DEBUG)/Etat/EnRoute.o: Etat/EnRoute.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/EnRoute.cpp -o $(OBJDIR_DEBUG)/Etat/EnRoute.o

$(OBJDIR_DEBUG)/Etat/EnChargeFacePlot.o: Etat/EnChargeFacePlot.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/EnChargeFacePlot.cpp -o $(OBJDIR_DEBUG)/Etat/EnChargeFacePlot.o

$(OBJDIR_DEBUG)/Etat/EnCharge.o: Etat/EnCharge.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/EnCharge.cpp -o $(OBJDIR_DEBUG)/Etat/EnCharge.o

$(OBJDIR_DEBUG)/BaseRobot/Objet.o: BaseRobot/Objet.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c BaseRobot/Objet.cpp -o $(OBJDIR_DEBUG)/BaseRobot/Objet.o

$(OBJDIR_DEBUG)/Etat/AVideFacePlot.o: Etat/AVideFacePlot.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/AVideFacePlot.cpp -o $(OBJDIR_DEBUG)/Etat/AVideFacePlot.o

$(OBJDIR_DEBUG)/Etat/AVide.o: Etat/AVide.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Etat/AVide.cpp -o $(OBJDIR_DEBUG)/Etat/AVide.o

$(OBJDIR_DEBUG)/BaseRobot/Robot.o: BaseRobot/Robot.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c BaseRobot/Robot.cpp -o $(OBJDIR_DEBUG)/BaseRobot/Robot.o

$(OBJDIR_DEBUG)/BaseRobot/Position.o: BaseRobot/Position.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c BaseRobot/Position.cpp -o $(OBJDIR_DEBUG)/BaseRobot/Position.o

$(OBJDIR_DEBUG)/BaseRobot/Plot.o: BaseRobot/Plot.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c BaseRobot/Plot.cpp -o $(OBJDIR_DEBUG)/BaseRobot/Plot.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/Etat
	rm -rf $(OBJDIR_DEBUG)/BaseRobot

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/Etat || mkdir -p $(OBJDIR_RELEASE)/Etat
	test -d $(OBJDIR_RELEASE)/BaseRobot || mkdir -p $(OBJDIR_RELEASE)/BaseRobot

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/Etat/Figer.o: Etat/Figer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/Figer.cpp -o $(OBJDIR_RELEASE)/Etat/Figer.o

$(OBJDIR_RELEASE)/Etat/EtatRobot.o: Etat/EtatRobot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/EtatRobot.cpp -o $(OBJDIR_RELEASE)/Etat/EtatRobot.o

$(OBJDIR_RELEASE)/Etat/EnRoute.o: Etat/EnRoute.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/EnRoute.cpp -o $(OBJDIR_RELEASE)/Etat/EnRoute.o

$(OBJDIR_RELEASE)/Etat/EnChargeFacePlot.o: Etat/EnChargeFacePlot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/EnChargeFacePlot.cpp -o $(OBJDIR_RELEASE)/Etat/EnChargeFacePlot.o

$(OBJDIR_RELEASE)/Etat/EnCharge.o: Etat/EnCharge.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/EnCharge.cpp -o $(OBJDIR_RELEASE)/Etat/EnCharge.o

$(OBJDIR_RELEASE)/BaseRobot/Objet.o: BaseRobot/Objet.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c BaseRobot/Objet.cpp -o $(OBJDIR_RELEASE)/BaseRobot/Objet.o

$(OBJDIR_RELEASE)/Etat/AVideFacePlot.o: Etat/AVideFacePlot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/AVideFacePlot.cpp -o $(OBJDIR_RELEASE)/Etat/AVideFacePlot.o

$(OBJDIR_RELEASE)/Etat/AVide.o: Etat/AVide.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Etat/AVide.cpp -o $(OBJDIR_RELEASE)/Etat/AVide.o

$(OBJDIR_RELEASE)/BaseRobot/Robot.o: BaseRobot/Robot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c BaseRobot/Robot.cpp -o $(OBJDIR_RELEASE)/BaseRobot/Robot.o

$(OBJDIR_RELEASE)/BaseRobot/Position.o: BaseRobot/Position.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c BaseRobot/Position.cpp -o $(OBJDIR_RELEASE)/BaseRobot/Position.o

$(OBJDIR_RELEASE)/BaseRobot/Plot.o: BaseRobot/Plot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c BaseRobot/Plot.cpp -o $(OBJDIR_RELEASE)/BaseRobot/Plot.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/Etat
	rm -rf $(OBJDIR_RELEASE)/BaseRobot

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

